# Generated by Django 5.2.1 on 2025-06-24 00:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255, unique=True)),
                ("socket", models.CharField(max_length=50)),
                ("n_cores", models.IntegerField()),
                ("base_clock_speed", models.FloatField()),
                ("boost_clock_speed", models.FloatField()),
                ("consumption", models.IntegerField()),
                (
                    "integrated_gpu",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("consumption", models.IntegerField()),
                ("vram", models.FloatField()),
                ("base_clock_speed", models.FloatField()),
                ("boost_clock_speed", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("socket", models.CharField(max_length=50)),
                ("board_size", models.CharField(max_length=50)),
                ("n_ram_slots", models.IntegerField()),
                ("memory_gen", models.CharField(max_length=50)),
                ("memory_max", models.IntegerField()),
                ("memory_speeds", models.CharField(max_length=400)),
                ("sata", models.IntegerField()),
                ("m2", models.IntegerField()),
                ("pcie_x1", models.IntegerField()),
                ("pcie_x4", models.IntegerField()),
                ("pcie_x8", models.IntegerField()),
                ("pcie_x16", models.IntegerField()),
                ("usb", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PSU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("power", models.IntegerField()),
                ("rate", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("generation", models.CharField(max_length=50)),
                ("size", models.IntegerField()),
                ("speed", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("io", models.CharField(max_length=50)),
                ("is_hdd", models.BooleanField()),
                ("rpm", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CurrentVolatileData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "product_name_on_source",
                    models.CharField(
                        help_text="Nome do produto como aparece na fonte original",
                        max_length=500,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL única do produto na fonte original",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(help_text="Nome da loja ou fonte", max_length=100),
                ),
                ("current_price", models.FloatField()),
                ("current_availability", models.BooleanField()),
                (
                    "last_checked",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dado Volátil Atual",
                "verbose_name_plural": "Dados Voláteis Atuais",
                "unique_together": {("url", "source")},
            },
        ),
        migrations.CreateModel(
            name="VolatileDataHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("product_name_on_source", models.CharField(max_length=500)),
                ("price", models.FloatField()),
                ("availability", models.BooleanField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "current_data_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="scraper.currentvolatiledata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Dado Volátil",
                "verbose_name_plural": "Histórico de Dados Voláteis",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
