# Generated by Django 5.2.1 on 2025-05-09 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("socket", models.CharField(max_length=50)),
                ("n_cores", models.IntegerField()),
                ("base_clock_speed", models.FloatField()),
                ("boost_clock_speed", models.FloatField()),
                ("consumption", models.IntegerField()),
                (
                    "integrated_gpu",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("consumption", models.IntegerField()),
                ("vram", models.IntegerField()),
                ("vram_speed", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("socket", models.CharField(max_length=50)),
                ("board_size", models.CharField(max_length=50)),
                ("n_ram_slots", models.IntegerField()),
                ("memory_gen", models.CharField(max_length=50)),
                ("memory_max", models.IntegerField()),
                ("memory_speeds", models.CharField(max_length=255)),
                ("sata", models.IntegerField()),
                ("m2", models.IntegerField()),
                ("pcie_x1", models.IntegerField()),
                ("pcie_x4", models.IntegerField()),
                ("pcie_x8", models.IntegerField()),
                ("pcie_x16", models.IntegerField()),
                ("usb", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PSU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("power", models.IntegerField()),
                ("rate", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("generation", models.CharField(max_length=50)),
                ("size", models.IntegerField()),
                ("speed", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("io", models.CharField(max_length=50)),
                ("is_hdd", models.BooleanField()),
                ("rpm", models.IntegerField()),
            ],
        ),
    ]
