# Generated by Django 5.2.1 on 2025-06-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpu",
            name="chipset",
            field=models.CharField(default="N/A", max_length=50),
        ),
    ]
