# Generated by Django 5.2.1 on 2025-05-15 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_alter_gpu_vram_alter_motherboard_memory_speeds"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volatile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("availability", models.BooleanField()),
                ("kind", models.CharField(max_length=50)),
            ],
        ),
    ]
