# Generated by Django 5.2.1 on 2025-05-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_volatile"),
    ]

    operations = [
        migrations.AddField(
            model_name="volatile",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
