services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "./run.sh"
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - ./backend/database/.env
    depends_on:
      - redis
    working_dir: /app

  frontend:
    # A construção agora usa o Dockerfile que criámos
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend